# Dependencies
markdown:         kramdown
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            air33
tagline:          '不恒其德或承之羞'
description:      '新的地方新的开始，不为别人只促自己'
url:              http://air33.github.io
baseurl:          /

author:
  name:           'air33'
  url:            http://weibo.com/u/2770731193

gems: [jekyll-paginate]
paginate:         5

# Custom vars
version:          1.1

github:
  repo:           https://github.com/air33/air33.github.io
